routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');
// User Settings Route
Route::get('/account-settings', 'UserController@index')->middleware('auth');
Route::put('/account-settings/update/{user}', [
	'as'	=>	'account.update',
	'uses' 	=> 	'UserController@update'
])->middleware('auth');
// Logout Route
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

//tables
Route::get('/tables/meals', 'TablesController@meals')->middleware('auth');
Route::get('/tables/orders/unclaimed', 'TablesController@unclaimed_orders')->middleware('auth');
Route::get('/tables/orders/all', 'TablesController@all_orders')->middleware('auth');
Route::get('/tables/feedbacks', 'TablesController@feedbacks')->middleware('auth');

//dropdowns
Route::get('/lists/meals', 'DropdownsController@meals');

//orders
Route::get('/orders/unclaimed', 'OrdersController@index_unclaimed')->middleware('auth');
Route::get('/orders/all', 'OrdersController@index_all')->middleware('auth');
Route::post('/orders/order-placement/new', 'OrdersController@store');
Route::get('/orders/order-placement/{order}/successful', function($order){
	return redirect('/')->with([
		'status'	=>	'Order #'.sprintf('%07d',$order).' placement successful.',
		// 'info'		=>	'Your order has been placed under Order #'.sprintf('%07d',$order)
	]);
});
Route::get('/orders/order-placement/{order}/failed', function($order){
	return redirect('/')->with([
		'status'	=>	'Order #'.sprintf('%07d',$order).' placement failed.',
		// 'info'		=>	'Your order has been placed under Order #'.sprintf('%07d',$order)
	]);
});
Route::get('/orders', 'OrdersController@index')->middleware('auth');
Route::get('/orders/view/{order}', 'OrdersController@show');
Route::put('/orders/claim/{order}', 'OrdersController@update')->name('orders.claim')->middleware('auth');
Route::get('/orders/unclaimed/count', 'OrdersController@unclaimed')->middleware('auth');
Route::get('/orders/all/count', 'OrdersController@all')->middleware('auth');
Route::get('/orders/search-form', 'OrdersController@search_form');
Route::post('/orders/search', 'OrdersController@search');

//feedbacks
Route::resource('/feedbacks', 'FeedbacksController');

//newsletter
Route::post('/ads/send/email', 'AdvertisementsController@email')->middleware('auth')->name('ad.sendmail');

//meals
Route::resource('/meals', 'MealsController');

//chat
Route::get('/chat', function(){
	return view('chat');
});
Route::post('/messages/send', 'MessagesController@send');
Route::get('/lists/messages', 'MessagesController@get');
Route::get('/messages', 'MessagesController@index')->middleware('auth');
Route::get('/messages/count', 'MessagesController@count')->middleware('auth');

//system settings
Route::get('/settings', 'SystemSettingsController@index')->middleware('auth');
Route::post('/settings/database/backup', 'SystemSettingsController@database_backup')->middleware('auth');

//generate reports
Route::get('/reports/list-of-orders', 'ReportsController@orders')->middleware('auth');
Route::get('/reports/list-of-customers', 'ReportsController@customers')->middleware('auth');
Route::post('/reports/sales', 'ReportsController@sales')->middleware('auth');
Route::get('/reports/receipt/order/{order}', 'ReportsController@receipt');

app/Meal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meal extends Model
{
    protected $fillable = [
    	'meal-desc',
    	'meal-price'
    ];
}

app/Http/Controllers/MealsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meal;

class MealsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $meals = Meal::all();

        // return view('admin.meals.meals')->with('meals',$meals);
        return view('admin.meals.index');
    }

    public function get()
    {
        $meals = Meal::all();

        return $meals;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'desc'  =>  'required',
        //     'price' =>  'required'
        // ]);

        $meal = new Meal;
        $meal->desc = $request["meal-desc"];
        $meal->price = $request["meal-price"];
        $meal->save();

        return redirect('/meals')->with('success','Meal added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meal = Meal::find($id);

        return view('admin.meals.view')->with('meal',$meal);
        // return $meal;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, [
        //     'desc'  =>  'required',
        //     'price' =>  'required'
        // ]);

        $meal = Meal::find($id);
        $meal->desc = $request->input("edit-meal-desc");
        $meal->price = $request->input("edit-meal-price");
        $meal->save();

        return redirect('/meals')->with('success','Meal edited successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $meal = Meal::find($id);
        $meal->delete();

        return redirect('/meals')->with('success','Meal deleted successfully.');
    }
}

resources/views/admin/meals/index.blade.php
@section('page-name')
	{{ config('app.name', 'Laravel') }} | Meals
@endsection

@extends('layouts.app')

@section('content')
	{{-- <div data-remodal-id="modalEditUsers">
		<button data-remodal-action="close" class="remodal-close"></button>
		<h5 class = "header">Edit user</h5>

	</div> --}}

	<div class = "row">
		<div class = "seven wide column">
			<div class = "ui small raised text segment">
				<h5 class = "ui header">Add meal</h5>

				<form id = "frmAddMeal" class = "ui small equal width form" method = "post" action = "{{ route('meals.store') }}">
					{{ csrf_field() }}

					<div class = "field">
						<label>Description:</label>
						<input type = "text" id = "meal-desc" name = "meal-desc" required autofocus>
					</div>

					<div class = "field">
						<label>Price:</label>
						<input type = "number" id = "meal-price" name = "meal-price" min = "0" step = "0.01" required>
					</div>

					<button type = "submit" class = "ui small primary button">Submit</button>
				</form>
			</div>
		</div>

		<div class = "column">
			<div class = "ui small raised text segment">
				<h5 class = "ui header">List of meals</h5>

				<table id = "tblListOfMeals" class = "ui small celled striped table" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>#</th>
							<th>Description</th>
							<th>Price</th>
							<th>Action</th>
						</tr>
					</thead>

					{{-- <tbody>
						@if(count($meals) > 0)
							@foreach($meals as $meal)
								<tr>
									<td>{{ $meal->id }}</td>
									<td>{{ $meal->desc }}</td>
									<td>{{ $meal->price }}</td>
									<td>
										<button type = "button" id = "btnEditMeal" class = "ui mini icon button">
											<i class = "eye icon"></i>
										</button>
									</td>
								</tr>
							@endforeach
						@else
							<tr>
								<td>No data available</td>
							</tr>
						@endif
					</tbody> --}}
				</table>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
	@if(session()->has('success'))
		<script type = "text/javascript">
			toastr.success('{{ session('success') }}');
		</script>
	@endif

	<script type = "text/javascript">
		$('#pgMeals').toggleClass('active',true);

		var tblListOfMeals = $('#tblListOfMeals').DataTable({
			processing: true,
			ajax:{
				url: '/tables/meals',
				dataSrc: '',
				serverside: true
			},
			columns: [
				{'data':'id'},
				{'data':'desc'},
				{'data':'price'},
				{'data':null}
			],
			columnDefs: [{
				targets: -1,
				data: null,
				defaultContent: '\
					<button id="btnViewMeal" class="ui mini icon button"><i class = "eye icon"></i></button>\
				',
				orderable: false
			},{
				searchable: true,
				orderable: true,
				targets: 0
			}],
			pageLength: 5
		});

		$('#tblListOfMeals tbody').on('click', '#btnViewMeal', function(event){
			var dataSelect = tblListOfMeals.row( $(this).parents('tr') ).data();
			var id = dataSelect['id'];
			self.location = '/meals/'+id+'/edit';
		});
	</script>
@endsection

resources/views/admin/meals/view.blade.php
@section('page-name')
	{{ config('app.name', 'Laravel') }} | Meals
@endsection

@extends('layouts.app')

@section('content')
	<div class = "row">
		<div class = "column"></div>
		<div class = "eight wide column">
			<div class = "ui small raised clearing text segment">
				<h5 class = "ui header">Edit meal</h5>

				<form id = "frmEditMeal" class = "ui small equal width form" method = "post" action = "{{ route('meals.update',$meal->id) }}">
					{{ csrf_field() }}
					{{ method_field('PUT') }}

					<div class = "field">
						<label>Description:</label>
						<input type = "text" id = "edit-meal-desc" name = "edit-meal-desc" value = "{{ $meal->desc }}" required autofocus>
					</div>

					<div class = "field">
						<label>Price:</label>
						<input type = "number" id = "edit-meal-price" name = "edit-meal-price" value = "{{ $meal->price }}" min = "0" step = "0.01" required>
					</div>

					<div class = "ui three small buttons">
						<a href = "/meal" role = "button" class = "ui small button">
							<i class = "left arrow icon"></i>
							Back
						</a>
						<button type = "submit" class = "ui small positive button">
							<i class = "send icon"></i>
							Submit
						</button>
						<button type = "button" id = "btnDeleteMeal" class = "ui small negative button">
							<i class = "trash icon"></i>
							Delete
						</button>
					</div>
				</form>

				<form id = "frmDeleteMeal" method = "post" action = "{{ route('meals.destroy',$meal->id) }}" hidden>
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
				</form>
			</div>
		</div>
		<div class = "column"></div>
	</div>
@endsection

@section('scripts')
	@if(session()->has('success'))
		<script type = "text/javascript">
			toastr.success('{{ session('success') }}');
		</script>
	@endif

	<script type = "text/javascript">
		$('#pgMeals').toggleClass('active',true);

		var tblListOfMeals = $('#tblListOfMeals').DataTable();

		$(document).on('click','#btnDeleteMeal',function(){
			if (confirm('Confirm this action?') == true) {
				$('#frmDeleteMeal').submit();
			}
		});
	</script>
@endsection